export enum StatutLivraison {
  EN_PREPARATION = 'EN_PREPARATION',
  EN_ATTENTE_EXPEDITION = 'EN_ATTENTE_EXPEDITION',
  EXPEDIEE = 'EXPEDIEE',
  EN_TRANSIT = 'EN_TRANSIT',
  LIVREE = 'LIVREE',
  ANNULEE = 'ANNULEE',
  RETOURNEE = 'RETOURNEE'
}